site_name: Unchained
site_description: Modern, high-performance Python web framework based on Django Ninja with FastDepends
site_url: https://unchained-framework.org
repo_url: https://github.com/Paperz-org/unchained
repo_name: Unchained
dev_addr: 127.0.0.1:8001

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - toc:
      permalink: true
      title: On this page

extra:
  generator: false

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Core:
    - Routing: core/routing.md
    - Models: core/models.md
    - Dependency Injection: core/dependency-injection.md
    - State Management: core/state.md
    - Admin Interface: core/admin.md
    - Lifespan: core/lifespan.md
    - CRUD: core/crud.md
    - Settings: core/settings.md
  - CRUD Operations:
    - Customizing: crud/customizing.md
  - CLI:
    - Commands: cli/commands.md
  - Contributing: contributing.md 