name: Development Workflow

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  update_comment:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Get CI Workflow Run Conclusion
        id: ci_status
        uses: poteto/get-workflow-run-conclusion@v1.0.1
        with:
          workflow_name: CI
          commit: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jobs: |
            lint
            build
        continue-on-error: true

      - name: Generate Comment Body
        id: generate_body
        run: |
          # Default to Pending if status not found or workflow hasn't run/completed
          LINT_STATUS=${{ steps.ci_status.outputs.lint_conclusion == 'success' && '✅ Success' || steps.ci_status.outputs.lint_conclusion == 'failure' && '❌ Failure' || steps.ci_status.outputs.lint_conclusion == 'cancelled' && '🚫 Cancelled' || '⏳ Pending' }}
          BUILD_STATUS=${{ steps.ci_status.outputs.build_conclusion == 'success' && '✅ Success' || steps.ci_status.outputs.build_conclusion == 'failure' && '❌ Failure' || steps.ci_status.outputs.build_conclusion == 'cancelled' && '🚫 Cancelled' || '⏳ Pending' }}

          # Add link to the workflow run if found
          RUN_ID=${{ steps.ci_status.outputs.run_id }}
          REPO_URL=${{ github.server_url }}/${{ github.repository }}
          WORKFLOW_RUN_URL=""
          if [[ -n "$RUN_ID" ]]; then
            WORKFLOW_RUN_URL="[View CI Run]($REPO_URL/actions/runs/$RUN_ID)"
          fi

          COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
          HELLO_WORLD_URL="$REPO_URL/actions/workflows/hello-world.yml"

          COMMENT_BODY=$(cat <<EOF
          ## PR Status for commit [\`$SHORT_SHA\`]($REPO_URL/commit/$COMMIT_SHA)

          | Check         | Status        |
          |---------------|---------------|
          | Lint          | $LINT_STATUS  |
          | Build/Test    | $BUILD_STATUS |

          $WORKFLOW_RUN_URL

          ---

          ### Manual Actions

          *   🚀 **Run Hello World:** [Click here to trigger]($HELLO_WORLD_URL) (Requires manual run confirmation)
              *   Status: *Not run yet*

          <!-- Sticky comment identifier: pr-status-comment -->
          EOF
          )

          # Escape special characters for JSON and set multiline output
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.generate_body.outputs.comment }}